CFLAGS_mtk_lpm_trace_event.o := -I$(src)
ccflags-y += -I$(srctree)/drivers/misc/mediatek/lpm/mtk_lpm_trace_event
ccflags-y += -I$(srctree)/drivers/misc/mediatek/lpm/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include

obj-y += mtk_lpm_trace_event.o
