ccflags-y += -I$(srctree)/drivers/misc/mediatek/lpm/mtk_lpm_fs
ccflags-y += -I$(srctree)/drivers/misc/mediatek/lpm/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include

obj-y += mtk_lp_kernfs.o
obj-y += mtk_lp_sysfs.o
obj-y += mtk_suspend_sysfs.o
obj-y += mtk_spm_sysfs.o
obj-y += mtk_lpm_sysfs.o
obj-y += mtk_lp_sysfs_procfs.o
